export const GET_CHARACTERS_LOADING = 'GET_CHARACTERS_LOADING';
export const GET_CHARACTERS_SUCCESSFUL = 'GET_CHARACTERS_SUCCESSFUL';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const FILTER_CHARACTERS_BY_HOUSE = 'FILTER_CHARACTERS_BY_HOUSE';