export const GET_CHARACTER_BY_ID = 'GET_CHARACTER_BY_ID';
export const GET_CHARACTER_BY_ID_SUCCESSFUL = 'GET_CHARACTER_BY_ID_SUCCESSFUL';
export const GET_CHARACTER_BY_ID_ERROR = ' GET_CHARACTER_BY_ID_ERROR';